// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: x50pay
  static const package = "x50pay";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName});

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/common/header_float_icon.jpg
  // ignore: non_constant_identifier_names
  final header_float_icon_jpg = const AssetResource(
      "assets/images/common/header_float_icon.jpg",
      packageName: null);

  /// asset: assets/images/common/header_icon.png
  // ignore: non_constant_identifier_names
  final header_icon = const AssetResource(
      "assets/images/common/header_icon.png",
      packageName: null);

  /// asset: assets/images/common/logo.jpg
  // ignore: non_constant_identifier_names
  final logo_jpg =
      const AssetResource("assets/images/common/logo.jpg", packageName: null);

  /// asset: assets/images/common/logo_150.jpg
  // ignore: non_constant_identifier_names
  final logo_150_jpg = const AssetResource("assets/images/common/logo_150.jpg",
      packageName: null);

  /// asset: assets/images/common/ouo.png
  // ignore: non_constant_identifier_names
  final ouo =
      const AssetResource("assets/images/common/ouo.png", packageName: null);

  /// asset: assets/images/login/login_banner.jpg
  // ignore: non_constant_identifier_names
  final login_banner_jpg = const AssetResource(
      "assets/images/login/login_banner.jpg",
      packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();

  /// asset: assets/texts/license.txt
  // ignore: non_constant_identifier_names
  final license_txt =
      const AssetResource("assets/texts/license.txt", packageName: null);
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/common/header_float_icon.jpg
  // ignore: non_constant_identifier_names
  AssetImage header_float_icon_jpg() {
    return AssetImage(asset.header_float_icon_jpg.keyName);
  }

  /// asset: assets/images/common/header_icon.png
  // ignore: non_constant_identifier_names
  AssetImage header_icon() {
    return AssetImage(asset.header_icon.keyName);
  }

  /// asset: assets/images/common/logo.jpg
  // ignore: non_constant_identifier_names
  AssetImage logo_jpg() {
    return AssetImage(asset.logo_jpg.keyName);
  }

  /// asset: assets/images/common/logo_150.jpg
  // ignore: non_constant_identifier_names
  AssetImage logo_150_jpg() {
    return AssetImage(asset.logo_150_jpg.keyName);
  }

  /// asset: assets/images/common/ouo.png
  // ignore: non_constant_identifier_names
  AssetImage ouo() {
    return AssetImage(asset.ouo.keyName);
  }

  /// asset: assets/images/login/login_banner.jpg
  // ignore: non_constant_identifier_names
  AssetImage login_banner_jpg() {
    return AssetImage(asset.login_banner_jpg.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();

  /// asset: assets/texts/license.txt
  // ignore: non_constant_identifier_names
  Future<String> license_txt() {
    final str = rootBundle.loadString(asset.license_txt.keyName);
    return str;
  }
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();
}
