// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore_for_file: depend_on_referenced_packages

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: x50pay
  static const package = "x50pay";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName});

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/appIcon/appstore.png
  // ignore: non_constant_identifier_names
  final appstore = const AssetResource("assets/images/appIcon/appstore.png",
      packageName: null);

  /// asset: assets/images/appIcon/playstore.png
  // ignore: non_constant_identifier_names
  final playstore = const AssetResource("assets/images/appIcon/playstore.png",
      packageName: null);

  /// asset: assets/images/common/header_icon_rsz.png
  // ignore: non_constant_identifier_names
  final header_icon_rsz = const AssetResource(
      "assets/images/common/header_icon_rsz.png",
      packageName: null);

  /// asset: assets/images/common/logo_150.jpg
  // ignore: non_constant_identifier_names
  final logo_150_jpg = const AssetResource("assets/images/common/logo_150.jpg",
      packageName: null);

  /// asset: assets/images/home/mari_level/ouo.png
  // ignore: non_constant_identifier_names
  final ouo = const AssetResource("assets/images/home/mari_level/ouo.png",
      packageName: null);

  /// asset: assets/images/home/top.png
  // ignore: non_constant_identifier_names
  final top =
      const AssetResource("assets/images/home/top.png", packageName: null);

  /// asset: assets/images/home/vts.png
  // ignore: non_constant_identifier_names
  final vts =
      const AssetResource("assets/images/home/vts.png", packageName: null);

  /// asset: assets/images/scanPay/jkopay_logo.png
  // ignore: non_constant_identifier_names
  final jkopay_logo = const AssetResource(
      "assets/images/scanPay/jkopay_logo.png",
      packageName: null);

  /// asset: assets/images/scanPay/linepay_logo.png
  // ignore: non_constant_identifier_names
  final linepay_logo = const AssetResource(
      "assets/images/scanPay/linepay_logo.png",
      packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

  /// asset: assets/images/collab/shop-solid.svg
  // ignore: non_constant_identifier_names
  final shop_solid = const AssetResource("assets/images/collab/shop-solid.svg",
      packageName: null);

  /// asset: assets/images/common/spinner-solid.svg
  // ignore: non_constant_identifier_names
  final spinner_solid = const AssetResource(
      "assets/images/common/spinner-solid.svg",
      packageName: null);

  /// asset: assets/images/common/torii.svg
  // ignore: non_constant_identifier_names
  final torii =
      const AssetResource("assets/images/common/torii.svg", packageName: null);

  /// asset: assets/images/game/heart-circle-plus-solid.svg
  // ignore: non_constant_identifier_names
  final heart_circle_plus_solid = const AssetResource(
      "assets/images/game/heart-circle-plus-solid.svg",
      packageName: null);

  /// asset: assets/images/home/bolt-solid.svg
  // ignore: non_constant_identifier_names
  final bolt_solid = const AssetResource("assets/images/home/bolt-solid.svg",
      packageName: null);

  /// asset: assets/images/home/heart-regular.svg
  // ignore: non_constant_identifier_names
  final heart_regular = const AssetResource(
      "assets/images/home/heart-regular.svg",
      packageName: null);

  /// asset: assets/images/home/heart-solid.svg
  // ignore: non_constant_identifier_names
  final heart_solid = const AssetResource("assets/images/home/heart-solid.svg",
      packageName: null);

  /// asset: assets/images/home/shirt-solid.svg
  // ignore: non_constant_identifier_names
  final shirt_solid = const AssetResource("assets/images/home/shirt-solid.svg",
      packageName: null);

  /// asset: assets/images/quest/stamp.svg
  // ignore: non_constant_identifier_names
  final stamp =
      const AssetResource("assets/images/quest/stamp.svg", packageName: null);

  /// asset: assets/images/scanPay/p-solid.svg
  // ignore: non_constant_identifier_names
  final p_solid = const AssetResource("assets/images/scanPay/p-solid.svg",
      packageName: null);
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();

  /// asset: assets/texts/license.txt
  // ignore: non_constant_identifier_names
  final license_txt =
      const AssetResource("assets/texts/license.txt", packageName: null);
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/appIcon/appstore.png
  // ignore: non_constant_identifier_names
  AssetImage appstore() {
    return AssetImage(asset.appstore.keyName);
  }

  /// asset: assets/images/appIcon/playstore.png
  // ignore: non_constant_identifier_names
  AssetImage playstore() {
    return AssetImage(asset.playstore.keyName);
  }

  /// asset: assets/images/common/header_icon_rsz.png
  // ignore: non_constant_identifier_names
  AssetImage header_icon_rsz() {
    return AssetImage(asset.header_icon_rsz.keyName);
  }

  /// asset: assets/images/common/logo_150.jpg
  // ignore: non_constant_identifier_names
  AssetImage logo_150_jpg() {
    return AssetImage(asset.logo_150_jpg.keyName);
  }

  /// asset: assets/images/home/mari_level/ouo.png
  // ignore: non_constant_identifier_names
  AssetImage ouo() {
    return AssetImage(asset.ouo.keyName);
  }

  /// asset: assets/images/home/top.png
  // ignore: non_constant_identifier_names
  AssetImage top() {
    return AssetImage(asset.top.keyName);
  }

  /// asset: assets/images/home/vts.png
  // ignore: non_constant_identifier_names
  AssetImage vts() {
    return AssetImage(asset.vts.keyName);
  }

  /// asset: assets/images/scanPay/jkopay_logo.png
  // ignore: non_constant_identifier_names
  AssetImage jkopay_logo() {
    return AssetImage(asset.jkopay_logo.keyName);
  }

  /// asset: assets/images/scanPay/linepay_logo.png
  // ignore: non_constant_identifier_names
  AssetImage linepay_logo() {
    return AssetImage(asset.linepay_logo.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

  /// asset: assets/images/collab/shop-solid.svg
  // ignore: non_constant_identifier_names
  AssetSvg shop_solid({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.shop_solid.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/common/spinner-solid.svg
  // ignore: non_constant_identifier_names
  AssetSvg spinner_solid({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.spinner_solid.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/common/torii.svg
  // ignore: non_constant_identifier_names
  AssetSvg torii({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.torii.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/game/heart-circle-plus-solid.svg
  // ignore: non_constant_identifier_names
  AssetSvg heart_circle_plus_solid(
      {required double width, required double height}) {
    final imageProvider = AssetSvg(asset.heart_circle_plus_solid.keyName,
        width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/home/bolt-solid.svg
  // ignore: non_constant_identifier_names
  AssetSvg bolt_solid({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.bolt_solid.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/home/heart-regular.svg
  // ignore: non_constant_identifier_names
  AssetSvg heart_regular({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.heart_regular.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/home/heart-solid.svg
  // ignore: non_constant_identifier_names
  AssetSvg heart_solid({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.heart_solid.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/home/shirt-solid.svg
  // ignore: non_constant_identifier_names
  AssetSvg shirt_solid({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.shirt_solid.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/quest/stamp.svg
  // ignore: non_constant_identifier_names
  AssetSvg stamp({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.stamp.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/scanPay/p-solid.svg
  // ignore: non_constant_identifier_names
  AssetSvg p_solid({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.p_solid.keyName, width: width, height: height);
    return imageProvider;
  }
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();

  /// asset: assets/texts/license.txt
  // ignore: non_constant_identifier_names
  Future<String> license_txt() {
    final str = rootBundle.loadString(asset.license_txt.keyName);
    return str;
  }
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();
}
